### ISSUE TITLE
BOHMap can crash JVM

### ISSUE THREAD

**Issue by vkazanov** [cfelde/BinaryOffheapHashMap#1]
BOHMap calculates offset into the partition using the following code:

```java
 final int hash = Math.abs(hashFunction.apply(keyData));
 final long offset = hash % partitionCount;
```

If `hashFunction` returns `Integer.MIN_VALUE` (i.e. -2147483648) Math.abs will return a negative number. A native offset into a buffer most of the time will crash the process, if not worse. 

Check out, for example, [this explanation](https://stackoverflow.com/questions/5444611/math-abs-returns-wrong-value-for-integer-min-value ).

This can be easily fixed by doing something like this instead:

```java
final long offset = Math.abs(hashFunction.apply(keyData) % partitionCount);
```

I actually have a proper fix. Should I open a PR?

**Comment by sztanko** [comment]
Also wanted to mention we are using BOHMap in https://github.com/sztanko/cubedb. Thank you very much for this!

**Comment by cfelde** [comment]
Hi,

Good catch, and thanks for the proposed fix. Glad to see someone is using this 👍 

I'll look to get this in by this week, and feel free to open a PR if you want.

**Comment by vkazanov** [comment]
Here you go :-)
